iTwin/mobile-sdk-ios

- Sources/ITwinMobile/ITMApplication.swift
The redirection of console messages was not working, this seems to fix it by waiting until the webview is loaded.
> Delay attachment of the logger until the webview is loaded.

- .vscode/launch.json
- newVersion.py
* Add changeui/bumpui commands
* Add changesamples/bumpsamples commands
* Add bumpbranch command
* Move samples functionality into changesamples
* Add updates of Xcode projects
* Fix replaceall to track matches, not replacements
* Fix version regexes
* Fix backslash escaping
* Add updates to ThirdPartyAuth sample
* Fix release version lookups
* Update get_versions to throw on failure instead of returning False
* Add help epilog with steps
> More newVersion.py changes:

- .github/CODEOWNERS
Update so that @itwin/mobilesdkadmins is the only entry in CODEOWNERS.
> Update CODEOWNERS to only contain a team

- Sources/ITwinMobile/ITMActionSheet.swift
- Sources/ITwinMobile/ITMAlert.swift
- Sources/ITwinMobile/ITMNativeUI.swift
The Android version of ITMNativeUI already worked this way, and I felt that it was better than the iOS way, so I updated this iOS API to match. I wanted that to happen before the official 1.0 release.
Note that there will be a separate PR to update mobile-samples.
> Refactor native UI API to improve and better match Android

- Sources/ITwinMobile/ITMApplication.swift
This makes it easier for users of the library, since they can do UI work in query handlers without having to declare them as MainActor or switching to the main thread.
> Make query handlers MainActor

- Sources/ITwinMobile/ITMActionSheet.swift
- Sources/ITwinMobile/ITMApplication.swift
- Sources/ITwinMobile/ITMMessenger.swift
- Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
Also fix:
* Data race when sending messages from Swift to JS
* Typo: frontendLaunchSuceeded -> frontendLaunchSucceeded
> Stop mixing Dispatch with Swift concurrency

- Sources/ITwinMobile/ITMMessenger.swift
Forcing the query that returns Void to be async didn't make sense, so this changes the Void query to itself use a Task so that it wouldn't be async.
That also removed the possibility of it throwing an error, so this also adds a detection of the "not implemented" error so that any other error would then still be logged. That detection logic showed deficiencies in ITMError, so those were corrected.
> Make one-way query non-async.

- Sources/ITwinMobile/ITMAuthorizationClient.swift
- Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
The old code would ask for the current token after signout. This would trigger a signin attempt.
> Fix raiseOnAccessTokenChanged to avoid loop

- newVersion.py
* Support iTwin 3.7.x
* Suppoert different names for Swift packages
> Fixes for newVersion.py:

- Sources/ITwinMobile/ITMApplication.swift
Since AppAuth-iOS crashes when run in a Rosetta Simulator, allow the user to disable auth entirely so that they can still run the samples in a Rosetta Simulator.
> Add support for ITMAPPLICATION_DISABLE_AUTH

- Sources/ITwinMobile/ITMApplication.swift
* `presentInView` doesn't work right in iOS 17.
* `presentHidden` might still work, but is inconsistent with `presentInView` now gone.
> Remove broken convenience functions:

- newVersion.py
I noticed warnings at runtime about \s being invalid, and discovered it was because the \ wasn't being escaped with another backslash. All of the places this are used appear to be optional spaces, and the files apparently don't contain those spaces, so the regexes worked even though they were broken.
> Fix newVersion.py \s escapes

- Sources/ITwinMobile/ITMActionSheet.swift
- Sources/ITwinMobile/ITMAlert.swift
- Sources/ITwinMobile/ITMAlertController.swift
- Sources/ITwinMobile/ITMApplication.swift
- Sources/ITwinMobile/ITMAssetHandler.swift
- Sources/ITwinMobile/ITMAuthorizationClient.swift
- Sources/ITwinMobile/ITMDevicePermissionsHelper.swift
- Sources/ITwinMobile/ITMGeoLocationManager.swift
- Sources/ITwinMobile/ITMLogger.swift
- Sources/ITwinMobile/ITMMessenger.swift
- Sources/ITwinMobile/ITMNativeUI.swift
- Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
- Sources/ITwinMobile/ITMObservers.swift
- Sources/ITwinMobile/ITMViewController.swift
- Sources/ITwinMobile/ITMWebViewLogger.swift
In addition to lots of internal refactoring and documentation cleanup, this includes the following public API changes:
* `ITMApplication.webViewLogger` can now be nil.
* `ITMApplication.createWebViewLogger` now returns optional
* `ITMApplication` no longer calls JS `window.Bentley_FinishLaunching()`
* `ITMWebViewLogger.name` is now public and var
* `ITMWebViewLogger.log` is now open
> Code cleanup.

- newVersion.py
* Fix appui-layout-react to not be part of appui
* Print new versions for non-core versioned packages
> newVersion.py non-core updates:

- Sources/ITwinMobile/ITMLogger.swift
Note: an `enabled` flag was also added to the Android `ITMLogger`.
> Allow ITMLogger to be disabled

- Sources/ITwinMobile/ITMApplication.swift
This (hopefully) results in more idomatic Swift code.
Note: The new `ConfigStringPair` type will also be used in mobile-samples.
> Use `for case let` and `for ... where`

- newVersion.py
Version updates of dependent libraries can result in lint errors. Verify that that hasn't happened before pushing changes that include those version updates.
> Perform lint check before pushing changes

- .vscode/launch.json
- newVersion.py
* Correctly determine latest version of npm packages.
* Print node and npm versions on stdout instead of stderr.
Enhancement: print the python version being used.
> Fix version-related problems in newVersion.py:

- Sources/ITwinMobile/ITMApplication.swift
This is reported to crash on some unspecified future iOS version, and all iTwin Mobile-based apps should be using either the imodeljs URL scheme for running locally or the http URL scheme for running with a React debug server.
> Don't try to allow file URL access from webView

- Sources/ITwinMobile/ITMApplication.swift
- Sources/ITwinMobile/ITMObservers.swift
- Sources/ITwinMobile/ITMViewController.swift
- Sources/ITwinMobile/ITwinMobile.docc/ITwinMobile.md
A user of iTwin Mobile SDK discovered that since ITMApplication is a singleton, the observers that are added in `ITMApplication.viewWillAppear` were leaking (along with the associated view controller) any time the view controller in question closed. This fixes that by having the observers have a weak reference to the view controller so that the view controller will never leak, as well as adding a new `ITMApplication.viewWillDisappear` to clean up the observers as each view controller closes (and calling that from `ITMViewController`.
> Fix leaked observers in ITMApplication
