Sources/ITwinMobile/ITMApplication.swift
There will be a PR with the same name in iTwin/mobile-samples. These two must be used together.
=> Automate handling of ITMAppConfig.json settings.

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMMessenger.swift
- Added `configData` member variable to ITMApplication that gets loaded during initialization.
- Added `ITMMessenger.isLoggingEnabled`.
- Added support for `ITMAPPLICATION_MESSAGE_LOGGING` and `ITMAPPLICATION_FULL_MESSAGE_LOGGING` config vars.
=> Configuration data and message logging enhancements.

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMViewController.swift
@toddsouthenbentley @Carl-Hinkle 
**Note:** Do **not** merge this PR until after a related PR in iTwin/mobile-samples is ready to merge. Both PRs depend on each other, so they should be merged as close to the same time as possible. That other PR is not yet created. I hope to have that done some time later today.
=> Updates needed for ThirdPartyAuth sample

newVersion.py
* Switch to Python3.
* Support iTwin 3 instead of iModelJS 2.19.x
* Print message when not enough replacements happen.
=> Updates to newVersion.py:

newVersion.py
* Add branch command.
* Clean up diffs checks.
* Remove remaining references to mobile-sdk-samples.
* Don't bump without force if there are already local changes.
* Rename allDirsHaveDiffs and someDirsHaveDiffs.
* Verify no changes before running changeCommand.
* Verify sub-commands succeed in all command, and abort if not.
* Don't print that action is being taken until we're sure it's going to happen.
=> More improvements to newVersion.py:

newVersion.py
* Raise exceptions for failures.
* Change from camelCase to snake_case for function, variable, and parameter names.
=> Make newVersion.py more python-like:

.vscode/launch.json
This has two separate configurations, one for bump, and one for samples. Others can be added as needed, and VS Code lets you pick the one you want from the Debugger sidebar.
=> Add launch.json for debugging newVersion.py

newVersion.py
I can't test this without first merging it into main because doing so would create a release PR for these same changes.
=> Add (untested) pr1 command to newVersion.py.

newVersion.py
Also, allow it to be run from a different directory so that a modified copy of the script can run without getting pushed to GitHub.
=> Update newVersion.py not to use PRs.

newVersion.py
There were three problems:
* Got to code that hadn't executed in that way before, and it threw an exception.
* Expectations that iTwin/mobile-sdk-ios would be released early resulted in the wrong version number for stage2 and stage3.
* Trying to update the samples before the iTwin/mobile-sdk-ios release was impossible.
=> Fix problems caused by moving all releases to last.

newVersion.py
My earlier fix broke it under a different code path.
=> Fix new_mobile check.

.vscode/launch.json, newVersion.py
* Add changeitwin/bumpitwin commands.
* Fix build.gradle regexes.
=> newVersion.py updates:

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMMessenger.swift
Also improve doc comments now that Xcode autocompletes after ``
=> Add registerMessageHandler convenience functions

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMMessenger.swift
Also add one more MainActor tag that was missing before.
=> Remove registerMessageHandler

Sources/ITwinMobile/ITMAlert.swift, Sources/ITwinMobile/ITMAlertController.swift, Sources/ITwinMobile/ITMApplication.swift
See: https://developer.apple.com/wwdc21/10256
=> Refactor out for loops where appropriate

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMGeoLocationManager.swift, Sources/ITwinMobile/ITMMessenger.swift
Minimize the number of for loops used, and make them as far down the API stack as possible.
=> More for loop cleanup

.vscode/launch.json, newVersion.py
* Support iTwin 3.4.x and 3.5.x
* Allow an arbitrary number of base versions in search
=> Base version fixes:

Sources/ITwinMobile/ITMActionSheet.swift, Sources/ITwinMobile/ITMAlertController.swift, Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMAuthorizationClient.swift, Sources/ITwinMobile/ITMDevicePermissionsHelper.swift, Sources/ITwinMobile/ITMGeoLocationManager.swift, Sources/ITwinMobile/ITMMessenger.swift, Sources/ITwinMobile/ITMNativeUI.swift, Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift, Sources/ITwinMobile/ITMViewController.swift, Sources/ITwinMobile/ITMWebViewLogger.swift
* Git rid of "self." where it isn't needed.
* Add "[self]" capture to escaping closures
* Rename error function to createError to avoid compiler error
=> Cleanup usage of "self."

Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
Note: userInfo was never used, but didn't work on QA ims.
=> Allow usage of QA API servers.

Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
Also clean up OIDC auth client class
=> Revoke tokens during signout

Sources/ITwinMobile/ITMApplication.swift, Sources/ITwinMobile/ITMAuthorizationClient.swift, Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
* Create simple async wrappers to clean up code flow.
* Fix problems that were present in old logic.
* Add prompt:login to additional auth params.
* Fix MainActivity problems in auth flow
=> Refactor ITMOIDCAuthClient:

Sources/ITwinMobile/ITMMessenger.swift
The compiler bug only produces a warning and not an error, but this gets rid of the warning.
=> Work around Xcode 14.3 compiler bug

newVersion.py
There's no real way to test these changes without a release
=> Hopefully fix Package.resolved processing

Sources/ITwinMobile/ITMMessenger.swift
Also create async Void query convenience function
=> Rename non-async Void query to send

newVersion.py
* Added presentation-components to the list of non-core packages
* Created lists of packages that will share different versions for future enhancement to automatically determine their versions.
=> Fix and prep for future enhancement of newVersion

Sources/ITwinMobile/ITMGeoLocationManager.swift
* User can set threshold time when the "last location" is used instead of asking for a new one.
* Also updated `[String: Any]` types to `JSON`
=> Add support for "last location"

Sources/ITwinMobile/ITMApplication.swift
The device rotation animation would cause the web view to be hidden after the animation if it was un-hidden during the animation.
=> Fix webView isHidden change being lost

Sources/ITwinMobile/ITMKeychainHelper.swift, Sources/ITwinMobile/ITMOIDCAuthorizationClient.swift
This is a fix for a reported possible security vulnerability.
=> Remove vulnerable functionality from ITMKeychainHelper
